In [2]:
import numpy
import pandas
import sklearn
import seaborn
import matplotlib.pyplot as pltk
from pylab import rcParams
rcParams['figure.figsize']=10,8
from sklearn import datasets,linear_model
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
#creating dataframe
book_df = pandas.read_csv('C:/Users/SCHOOL/Desktop/Book_Rating.csv')

In [5]:
#check the data
book_df

           rowid  User-ID        ISBN  Book-Rating
0              0   276725  034545104X            0
1              1   276726   155061224            5
2              2   276727   446520802            0
3              3   276729  052165615X            3
4              4   276729   521795028            6
5              5   276733  2080674722            0
6              6   276736  3257224281            8
7              7   276737   600570967            6
8              8   276744  038550120X            7
9              9   276745   342310538           10
10            10   276746   425115801            0
11            11   276746   449006522            0
12            12   276746   553561618            0
13            13   276746  055356451X            0
14            14   276746   786013990            0
15            15   276746   786014512            0
16            16   276747    60517794            9
17            17   276747   451192001            0
18            18   276747   609801279            0
19            19   276747   671537458            9
20            20   276747   679776818            8
21            21   276747   943066433            7
22            22   276747  1570231028            0
23            23   276747  1885408226            7
24            24   276748   747558167            6
25            25   276748  3442437407            0
26            26   276751  033390804X            0
27            27   276751  3596218098            8
28            28   276754   684867621            8
29            29   276755   451166892            5
...          ...      ...         ...          ...
1048545  1048545   250764   449221180            0
1048546  1048546   250764   449221873            0
1048547  1048547   250764   449238342            0
1048548  1048548   250764   449701956            0
1048549  1048549   250764   449907481            0
1048550  1048550   250764   451130995            0
1048551  1048551   250764   451145097            0
1048552  1048552   250764   451150406            0
1048553  1048553   250764   451157516            0
1048554  1048554   250764   451160533            0
1048555  1048555   250764   451173139            0
1048556  1048556   250764   451180410            0
1048557  1048557   250764   451188497            0
1048558  1048558   250764   451191013            0
1048559  1048559   250764   451191692            0
1048560  1048560   250764   451192001            0
1048561  1048561   250764   451193911            0
1048562  1048562   250764   451197232            0
1048563  1048563   250764   451202309            0
1048564  1048564   250764   451202953            0
1048565  1048565   250764   451203615            0
1048566  1048566   250764   451205626            0
1048567  1048567   250764   451206711            0
1048568  1048568   250764   451400763            0
1048569  1048569   250764   451401387            0
1048570  1048570   250764   451410777            0
1048571  1048571   250764   452264464            8
1048572  1048572   250764  048623715X            0
1048573  1048573   250764   486256588            0
1048574  1048574   250764   515069434            0

[1048575 rows x 4 columns]

In [100]:
#take dependent and independent variables seperation
book_df_x=book_df[['User-ID','ISBN']]
book_df_y=book_df[['Book-Rating']]

In [101]:
book_df_x
book_df_y

         Book-Rating
0                  0
1                  5
2                  0
3                  3
4                  6
5                  0
6                  8
7                  6
8                  7
9                 10
10                 0
11                 0
12                 0
13                 0
14                 0
15                 0
16                 9
17                 0
18                 0
19                 9
20                 8
21                 7
22                 0
23                 7
24                 6
25                 0
26                 0
27                 8
28                 8
29                 5
...              ...
1048545            0
1048546            0
1048547            0
1048548            0
1048549            0
1048550            0
1048551            0
1048552            0
1048553            0
1048554            0
1048555            0
1048556            0
1048557            0
1048558            0
1048559            0
1048560            0
1048561            0
1048562            0
1048563            0
1048564            0
1048565            0
1048566            0
1048567            0
1048568            0
1048569            0
1048570            0
1048571            8
1048572            0
1048573            0
1048574            0

[1048575 rows x 1 columns]

In [102]:
#split train and test set
x_train,x_test,y_train,y_test=train_test_split(book_df_x,book_df_y,test_size=0.20)

In [103]:
x_train,x_test,y_train,y_test

(         User-ID        ISBN
 800498    194514  8835600901
 208557     48268   451169514
 344311     82091  951311886X
 622276    150896   802487785
 570972    137190  2020220989
 820451    198711   590417916
 617930    149647  849550152X
 244742     56272   743252071
 945150    228998  044022165X
 857857    207369   971191522
 696047    169755   425080021
 191838     42458   671793543
 308079     73588   451181379
 1045907   250278   553212419
 339065     80908  848432365X
 515998    125039   316030864
 238023     55490   425098648
 954405    230635  031027771X
 538353    129368   425183750
 296612     70183   879514175
 646691    156269   312856660
 107096     24627   425177009
 1041008   249058  1551669153
 1036318   247752   140482121
 418787     99955   590437232
 989024    238008   380814803
 49393      11676   425171272
 612451    148154  8408020927
 519764    125774   515132020
 146690     32773   671700294
 ...          ...         ...
 189048     41698   439064872
 161372     35859   671726714
 996654    239063   312983336
 909463    221445   307100146
 924205    224948   517561107
 427821    102206   887308813
 554043    133375   375761411
 535235    129074   671450492
 251853     57412   821717030
 274181     63938   671020552
 73417      15654   671755064
 566838    136139   316246255
 679042    165308   449005577
 505694    123056   385314698
 898523    217375    60178221
 152412     34864   452264464
 603034    145619   440235960
 1006100   241614   345443284
 433330    103289  1865084530
 128138     29743   137551002
 233190     53846   941483029
 69607      14521   312963297
 259504     60244    64401308
 686783    167389   689804466
 536818    129358   373765169
 824165    198982     6551726
 747385    180819  8804473673
 590976    142524   671617389
 812722    197659   740705326
 1026493   245952    61051837

 [838860 rows x 2 columns],          User-ID        ISBN
 954446    230687   446611867
 923056    224764   451195493
 13786       1903   439139597
 950789    230427  3462033204
 957069    231210   801037182
 569416    136473   553290851
 408800     98391    45120561
 667206    162266   345370139
 926115    225199   812571290
 236030     54969  3442447666
 31459       7326   451453824
 235314     54656    99387913
 740050    178919   140390197
 85100      18012   684841347
 497442    119858   135462681
 594099    143253   307988619
 818422    198711   439133211
 361029     87141    60913916
 88150      19285   241139988
 691105    168144  1891620150
 152297     34801   375708669
 384344     93047   316143464
 285821     68309   886775426
 732559    177090   451180321
 944950    228998   373710933
 637913    153662  1575665611
 16189       2719   441009700
 846795    204864   446311812
 542609    130474   515121487
 149157     33763   842342702
 ...          ...         ...
 596024    143718   525947051
 455066    109363   451459539
 395575     95359   140070206
 10908        507   821769340
 58928      11677   950442341
 494214    118533    60172126
 557725    134415   671657860
 242411     55793   743418220
 476803    114178   345335643
 639102    154070  1882413601
 999261    240033   380796171
 930058    225886   553273469
 724652    175003   446600342
 736474    177688  3453186834
 188136     41359   747260338
 46316      11676  014016930X
 882879    212923   451163516
 1024521   245740   440225701
 2549      277639   446302066
 610437    147839   743405897
 676845    164675   828905444
 417300     99227   553267892
 61780      12538   553213148
 725960    175070   312978383
 904357    219301   743486226
 442123    105973   770423000
 686311    167300   679642579
 913367    222488  3593367750
 589100    142147    15607321
 829707    200674   380008920

 [209715 rows x 2 columns],          Book-Rating
 800498             0
 208557             0
 344311             8
 622276             0
 570972             0
 820451             0
 617930             7
 244742             0
 945150             0
 857857             0
 696047             0
 191838             8
 308079             0
 1045907            0
 339065             8
 515998             0
 238023            10
 954405             0
 538353             0
 296612             0
 646691             7
 107096             8
 1041008            8
 1036318            0
 418787             5
 989024             7
 49393              7
 612451             0
 519764             0
 146690             6
 ...              ...
 189048             0
 161372             0
 996654             0
 909463             0
 924205             0
 427821             9
 554043             6
 535235             8
 251853             0
 274181             0
 73417              7
 566838             0
 679042             0
 505694             0
 898523             0
 152412             0
 603034             0
 1006100            0
 433330             0
 128138             0
 233190            10
 69607              0
 259504             9
 686783             8
 536818             0
 824165             0
 747385             7
 590976             0
 812722            10
 1026493            7

 [838860 rows x 1 columns],          Book-Rating
 954446             0
 923056             0
 13786              0
 950789             0
 957069             0
 569416             0
 408800             9
 667206            10
 926115             9
 236030             5
 31459              0
 235314             8
 740050             0
 85100              0
 497442             8
 594099             0
 818422             0
 361029             8
 88150              9
 691105             0
 152297             7
 384344             8
 285821             8
 732559             0
 944950             7
 637913             0
 16189              5
 846795             0
 542609             0
 149157            10
 ...              ...
 596024             0
 455066             0
 395575             0
 10908              0
 58928              0
 494214             0
 557725             9
 242411             6
 476803             0
 639102             8
 999261             0
 930058             0
 724652             0
 736474             0
 188136             0
 46316              0
 882879             0
 1024521            0
 2549               0
 610437             5
 676845             0
 417300             0
 61780              0
 725960             0
 904357             0
 442123             0
 686311             8
 913367             0
 589100             8
 829707             0

 [209715 rows x 1 columns])

In [104]:
#we will perform z-score normalization on both these
userid_scaler=StandardScaler()
userid_scaler.fit(pandas.DataFrame(x_train['User-ID']))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [105]:
x_train[['User-ID']]=userid_scaler.transform(x_train[['User-ID']])

In [106]:
x_train

          User-ID        ISBN
800498   0.889267  8835600901
208557  -1.081100   451169514
344311  -0.625404  951311886X
622276   0.301603   802487785
570972   0.116943  2020220989
820451   0.945813   590417916
617930   0.284776  849550152X
244742  -0.973262   743252071
945150   1.353869  044022165X
857857   1.062462   971191522
696047   0.555690   425080021
191838  -1.159378   671793543
308079  -0.739964   451181379
1045907  1.640573   553212419
339065  -0.641342  848432365X
515998  -0.046767   316030864
238023  -0.983798   425098648
954405   1.375924  031027771X
538353   0.011557   425183750
296612  -0.785840   879514175
646691   0.373994   312856660
107096  -1.399614   425177009
1041008  1.624136  1551669153
1036318  1.606541   140482121
418787  -0.384723   590437232
989024   1.475260   380814803
49393   -1.574103   425171272
612451   0.264661  8408020927
519764  -0.036864   515132020
146690  -1.289863   671700294
...           ...         ...
189048  -1.169617   439064872
161372  -1.248286   671726714
996654   1.489474   312983336
909463   1.252107   307100146
924205   1.299303   517561107
427821  -0.354395   887308813
554043   0.065544   375761411
535235   0.007596   671450492
251853  -0.957903   821717030
274181  -0.869979   671020552
73417   -1.520507   671755064
566838   0.102783   316246255
679042   0.495776   449005577
505694  -0.073484   385314698
898523   1.197273    60178221
152412  -1.261692   452264464
603034   0.230507   440235960
1006100  1.523844   345443284
433330  -0.339804  1865084530
128138  -1.330687   137551002
233190  -1.005948   941483029
69607   -1.535772   312963297
259504  -0.919748    64401308
686783   0.523813   689804466
536818   0.011423   373765169
824165   0.949464     6551726
747385   0.704755  8804473673
590976   0.188808   671617389
812722   0.931640   740705326
1026493  1.582289    61051837

[838860 rows x 2 columns]

In [107]:
#we will perform encoder
isbn_encoder=preprocessing.LabelEncoder()
isbn_encoder.fit(pandas.DataFrame(x_train['ISBN']))

LabelEncoder()

In [108]:
x_train[['ISBN']]=isbn_encoder.transform(x_train['ISBN'])

In [109]:
x_train

          User-ID    ISBN
800498   0.889267  259390
208557  -1.081100  145028
344311  -0.625404  273924
622276   0.301603  223428
570972   0.116943   55692
820451   0.945813  169614
617930   0.284776  248841
244742  -0.973262  208227
945150   1.353869    7334
857857   1.062462  277360
696047   0.555690  127814
191838  -1.159378  191262
308079  -0.739964  145375
1045907  1.640573  160163
339065  -0.641342  247784
515998  -0.046767   74513
238023  -0.983798  128051
954405   1.375924    2829
538353   0.011557  129744
296612  -0.785840  255706
646691   0.373994   71956
107096  -1.399614  129506
1041008  1.624136   28019
1036318  1.606541   24157
418787  -0.384723  170115
989024   1.475260  114513
49393   -1.574103  129310
612451   0.264661  238054
519764  -0.036864  153463
146690  -1.289863  189677
...           ...     ...
189048  -1.169617  130793
161372  -1.248286  190131
996654   1.489474   74105
909463   1.252107   66813
924205   1.299303  154581
427821  -0.354395  261552
554043   0.065544  109931
535235   0.007596  186438
251853  -0.957903  232658
274181  -0.869979  184935
73417   -1.520507  190813
566838   0.102783   75000
679042   0.495776  141185
505694  -0.073484  117202
898523   1.197273  173884
152412  -1.261692  148730
603034   0.230507  134248
1006100  1.523844   90425
433330  -0.339804   48631
128138  -1.330687   17829
233190  -1.005948  272555
69607   -1.535772   73419
259504  -0.919748  181237
686783   0.523813  200258
536818   0.011423  106564
824165   0.949464  182604
747385   0.704755  256909
590976   0.188808  188174
812722   0.931640  207267
1026493  1.582289  178468

[838860 rows x 2 columns]

In [110]:
#we will perform z-score normalization on both these
isbn_scaler=StandardScaler()
isbn_scaler.fit(pandas.DataFrame(x_train['ISBN']))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [111]:
x_train[['ISBN']]=isbn_scaler.transform(x_train[['ISBN']])

In [112]:
x_train

          User-ID      ISBN
800498   0.889267  1.704421
208557  -1.081100  0.138942
344311  -0.625404  1.903374
622276   0.301603  1.212144
570972   0.116943 -1.083960
820451   0.945813  0.475495
617930   0.284776  1.560018
244742  -0.973262  1.004061
945150   1.353869 -1.745923
857857   1.062462  1.950408
696047   0.555690 -0.096697
191838  -1.159378  0.771830
308079  -0.739964  0.143692
1045907  1.640573  0.346122
339065  -0.641342  1.545549
515998  -0.046767 -0.826323
238023  -0.983798 -0.093452
954405   1.375924 -1.807591
538353   0.011557 -0.070277
296612  -0.785840  1.653991
646691   0.373994 -0.861325
107096  -1.399614 -0.073535
1041008  1.624136 -1.462770
1036318  1.606541 -1.515636
418787  -0.384723  0.482353
989024   1.475260 -0.278771
49393   -1.574103 -0.076218
612451   0.264661  1.412357
519764  -0.036864  0.254407
146690  -1.289863  0.750134
...           ...       ...
189048  -1.169617 -0.055918
161372  -1.248286  0.756348
996654   1.489474 -0.831908
909463   1.252107 -0.931727
924205   1.299303  0.269711
427821  -0.354395  1.734016
554043   0.065544 -0.341493
535235   0.007596  0.705796
251853  -0.957903  1.338492
274181  -0.869979  0.685221
73417   -1.520507  0.765684
566838   0.102783 -0.819657
679042   0.495776  0.086336
505694  -0.073484 -0.241962
898523   1.197273  0.533946
152412  -1.261692  0.189618
603034   0.230507 -0.008623
1006100  1.523844 -0.608507
433330  -0.339804 -1.180617
128138  -1.330687 -1.602259
233190  -1.005948  1.884634
69607   -1.535772 -0.841299
259504  -0.919748  0.634600
686783   0.523813  0.894975
536818   0.011423 -0.387584
824165   0.949464  0.653313
747385   0.704755  1.670459
590976   0.188808  0.729559
812722   0.931640  0.990919
1026493  1.582289  0.596696

[838860 rows x 2 columns]

In [113]:
x_train_original=x_train
x_train=x_train.values
y_train=y_train.values

In [114]:
#create linear regression obj
simple_linear_regression=LinearRegression()

In [115]:
#fit the data
simple_linear_regression.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [116]:
x_test

         User-ID        ISBN
954446    230687   446611867
923056    224764   451195493
13786       1903   439139597
950789    230427  3462033204
957069    231210   801037182
569416    136473   553290851
408800     98391    45120561
667206    162266   345370139
926115    225199   812571290
236030     54969  3442447666
31459       7326   451453824
235314     54656    99387913
740050    178919   140390197
85100      18012   684841347
497442    119858   135462681
594099    143253   307988619
818422    198711   439133211
361029     87141    60913916
88150      19285   241139988
691105    168144  1891620150
152297     34801   375708669
384344     93047   316143464
285821     68309   886775426
732559    177090   451180321
944950    228998   373710933
637913    153662  1575665611
16189       2719   441009700
846795    204864   446311812
542609    130474   515121487
149157     33763   842342702
...          ...         ...
596024    143718   525947051
455066    109363   451459539
395575     95359   140070206
10908        507   821769340
58928      11677   950442341
494214    118533    60172126
557725    134415   671657860
242411     55793   743418220
476803    114178   345335643
639102    154070  1882413601
999261    240033   380796171
930058    225886   553273469
724652    175003   446600342
736474    177688  3453186834
188136     41359   747260338
46316      11676  014016930X
882879    212923   451163516
1024521   245740   440225701
2549      277639   446302066
610437    147839   743405897
676845    164675   828905444
417300     99227   553267892
61780      12538   553213148
725960    175070   312978383
904357    219301   743486226
442123    105973   770423000
686311    167300   679642579
913367    222488  3593367750
589100    142147    15607321
829707    200674   380008920

[209715 rows x 2 columns]

In [117]:
#we will perform z-score normalization on both these
userid_scaler=StandardScaler()
userid_scaler.fit(pandas.DataFrame(x_test['User-ID']))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [118]:
x_test[['User-ID']]=userid_scaler.transform(x_test[['User-ID']])

In [119]:
x_test

          User-ID        ISBN
954446   1.377082   446611867
923056   1.297260   451195493
13786   -1.706147   439139597
950789   1.373578  3462033204
957069   1.384130   801037182
569416   0.107398   553290851
408800  -0.405818    45120561
667206   0.455000   345370139
926115   1.303122   812571290
236030  -0.990998  3442447666
31459   -1.633064   451453824
235314  -0.995216    99387913
740050   0.679426   140390197
85100   -1.489053   684841347
497442  -0.116516   135462681
594099   0.198769   307988619
818422   0.946154   439133211
361029  -0.557429    60913916
88150   -1.471897   241139988
691105   0.534215  1891620150
152297  -1.262794   375708669
384344  -0.477836   316143464
285821  -0.811220   886775426
732559   0.654777   451180321
944950   1.354320   373710933
637913   0.339047  1575665611
16189   -1.695150   441009700
846795   1.029076   446311812
542609   0.026552   515121487
149157  -1.276783   842342702
...           ...         ...
596024   0.205036   525947051
455066  -0.257952   451459539
395575  -0.446679   140070206
10908   -1.724960   821769340
58928   -1.574427   950442341
494214  -0.134372    60172126
557725   0.079663   671657860
242411  -0.979893   743418220
476803  -0.193063   345335643
639102   0.344546  1882413601
999261   1.503034   380796171
930058   1.312381   553273469
724652   0.626651   446600342
736474   0.662836  3453186834
188136  -1.174415   747260338
46316   -1.574440  014016930X
882879   1.137684   451163516
1024521  1.579945   440225701
2549     2.009835   446302066
610437   0.260573   743405897
676845   0.487465   828905444
417300  -0.394551   553267892
61780   -1.562824   553213148
725960   0.627554   312978383
904357   1.223637   743486226
442123  -0.303638   770423000
686311   0.522841   679642579
913367   1.266587  3593367750
589100   0.183864    15607321
829707   0.972609   380008920

[209715 rows x 2 columns]

In [120]:
isbn_encoder=preprocessing.LabelEncoder()
isbn_encoder.fit(pandas.DataFrame(x_test['ISBN']))

LabelEncoder()

In [121]:
x_test[['ISBN']]=isbn_encoder.transform(x_test['ISBN'])

In [122]:
x_test

          User-ID    ISBN
954446   1.377082   55825
923056   1.297260   58578
13786   -1.706147   51601
950789   1.373578   34644
957069   1.384130   90563
569416   0.107398   65957
408800  -0.405818   58849
667206   0.455000   33403
926115   1.303122   93506
236030  -0.990998   31559
31459   -1.633064   59481
235314  -0.995216  109891
740050   0.679426    9409
85100   -1.489053   81384
497442  -0.116516    7041
594099   0.198769   25142
818422   0.946154   51579
361029  -0.557429   71697
88150   -1.471897   23162
691105   0.534215   19654
152297  -1.262794   42267
384344  -0.477836   28033
285821  -0.811220  103767
732559   0.654777   58295
944950   1.354320   40670
637913   0.339047   15543
16189   -1.695150   54021
846795   1.029076   54647
542609   0.026552   61861
149157  -1.276783   96973
...           ...     ...
596024   0.205036   63244
455066  -0.257952   59614
395575  -0.446679    7638
10908   -1.724960   95028
58928   -1.574427  107847
494214  -0.134372   70634
557725   0.079663   77381
242411  -0.979893   85273
476803  -0.193063   33033
639102   0.344546   19158
999261   1.503034   44366
930058   1.312381   65562
724652   0.626651   55438
736474   0.662836   32733
188136  -1.174415   86073
46316   -1.574440     689
882879   1.137684   58069
1024521  1.579945   52924
2549     2.009835   54598
610437   0.260573   85135
676845   0.487465   95444
417300  -0.394551   65444
61780   -1.562824   64713
725960   0.627554   27565
904357   1.223637   85767
442123  -0.303638   88414
686311   0.522841   79980
913367   1.266587   36055
589100   0.183864   12928
829707   0.972609   42939

[209715 rows x 2 columns]

In [123]:
#we will perform z-score normalization on both these
isbn_scaler=StandardScaler()
isbn_scaler.fit(pandas.DataFrame(x_test['ISBN']))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [124]:
x_test[['ISBN']]=isbn_scaler.transform(x_test[['ISBN']])

In [125]:
x_test

          User-ID      ISBN
954446   1.377082  0.064982
923056   1.297260  0.157466
13786   -1.706147 -0.076919
950789   1.373578 -0.646574
957069   1.384130  1.231971
569416   0.107398  0.405357
408800  -0.405818  0.166570
667206   0.455000 -0.688264
926115   1.303122  1.330839
236030  -0.990998 -0.750211
31459   -1.633064  0.187802
235314  -0.995216  1.881277
740050   0.679426 -1.494319
85100   -1.489053  0.923612
497442  -0.116516 -1.573870
594099   0.198769 -0.965784
818422   0.946154 -0.077659
361029  -0.557429  0.598186
88150   -1.471897 -1.032300
691105   0.534215 -1.150148
152297  -1.262794 -0.390486
384344  -0.477836 -0.868664
285821  -0.811220  1.675547
732559   0.654777  0.147959
944950   1.354320 -0.444136
637913   0.339047 -1.288253
16189   -1.695150  0.004378
846795   1.029076  0.025408
542609   0.026552  0.267755
149157  -1.276783  1.447309
...           ...       ...
596024   0.205036  0.314216
455066  -0.257952  0.192270
395575  -0.446679 -1.553814
10908   -1.724960  1.381969
58928   -1.574427  1.812611
494214  -0.134372  0.562476
557725   0.079663  0.789135
242411  -0.979893  1.054259
476803  -0.193063 -0.700694
639102   0.344546 -1.166811
999261   1.503034 -0.319972
930058   1.312381  0.392087
724652   0.626651  0.051981
736474   0.662836 -0.710772
188136  -1.174415  1.081134
46316   -1.574440 -1.787259
882879   1.137684  0.140367
1024521  1.579945 -0.032475
2549     2.009835  0.023762
610437   0.260573  1.049623
676845   0.487465  1.395944
417300  -0.394551  0.388123
61780   -1.562824  0.363566
725960   0.627554 -0.884386
904357   1.223637  1.070854
442123  -0.303638  1.159778
686311   0.522841  0.876446
913367   1.266587 -0.599172
589100   0.183864 -1.376102
829707   0.972609 -0.367911

[209715 rows x 2 columns]

In [126]:
#make predictions using trainning sets
y_pred=simple_linear_regression.predict(pandas.DataFrame(x_test))

In [127]:
y_pred

array([[2.62233461],
       [2.64121989],
       [3.2015524 ],
       ...,
       [2.61643095],
       [2.79041887],
       [2.68156049]])

In [128]:
print(r2_score(y_test,y_pred))

0.002799382268098616

In [129]:
#make mean squared error using trainning sets
print("mean squared error:%.1f"% mean_squared_error(y_test,y_pred))

mean squared error:14.8

In [130]:
#make mean absolute error using trainning sets
print("mean absolute error:%2f"% mean_absolute_error(y_test,y_pred))

mean absolute error:3.576897

In [131]:
y_pred

array([[2.62233461],
       [2.64121989],
       [3.2015524 ],
       ...,
       [2.61643095],
       [2.79041887],
       [2.68156049]])

# naive bayes

In [132]:
#train the model using training sets
naive_bayes=GaussianNB()
naive_bayes.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [133]:
#make predictions using training sets
y_pred=naive_bayes.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.6215864387382877

# random forest

In [134]:
#train the model using training sets
random_forest=RandomForestClassifier()
random_forest.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [ ]:
#make predictions using training sets
y_pred=random_forest.predict(x_test)

In [136]:
print(accuracy_score(y_test,y_pred))

0.536065612855542

# decision tree

In [137]:
#train the model using training sets
decision_tree=tree.DecisionTreeClassifier()

In [138]:
decision_tree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [139]:
#check on test data
y_pred=decision_tree.predict(x_test)
y_pred_prob=decision_tree.predict_proba(x_test)

In [140]:
print(accuracy_score(y_test,y_pred))

0.3633645661969816

In [142]:
mean=30
sigma=10
isbn=numpy.sort(numpy.random.normal(mean,sigma,50).astype(int))
bookrating=numpy.sort(numpy.random.normal(mean,sigma,50).astype(int))
plt.scatter(isbn,bookrating)

NameError: name 'plt' is not defined